// WASM engine loader + typed client. The wasm-bindgen output is generated by
// `scripts/build-wasm.sh` into `src/wasm/`, then imported here.
import initWasm, { process as wasmProcess } from './wasm/calcsim_wasm.js'
import wasmUrl from './wasm/calcsim_wasm_bg.wasm?url'

/** Mirrors `calcsim_core::Analysis` (serde JSON). */
export interface Analysis {
  ok: boolean
  error?: string
  input: string
  input_latex: string
  derivative: string
  derivative_latex: string
  integral: string
  integral_latex: string
  integral_symbolic: boolean
  definite_value: number | null
  x_min: number
  x_max: number
  xs: number[]
  ys: number[] // f(x)
  dys: number[] // f'(x)
  fs: number[] // F(x) = ∫[x_min, x] f(t) dt
}

let initPromise: Promise<void> | null = null

/** Initialise the WASM module once (safe to call repeatedly). */
export function ensureEngine(): Promise<void> {
  if (!initPromise) {
    initPromise = initWasm({ module_or_path: wasmUrl }).then(() => undefined)
  }
  return initPromise
}

/** Run the full analysis pipeline (parse → diff → integrate → sample). */
export function analyze(
  input: string,
  xMin: number,
  xMax: number,
  samples = 400,
): Analysis {
  return JSON.parse(wasmProcess(input, xMin, xMax, samples)) as Analysis
}
