// WASM engine loader + typed client. The wasm-bindgen output is generated by
// `scripts/build-wasm.sh` into `src/wasm/`, then imported here.
import initWasm, {
  process as wasmProcess,
  ac_power as wasmAcPower,
} from './wasm/calcsim_wasm.js'
import wasmUrl from './wasm/calcsim_wasm_bg.wasm?url'

/** Mirrors `calcsim_core::Analysis` (serde JSON). */
export interface Analysis {
  ok: boolean
  error?: string
  input: string
  input_latex: string
  derivative: string
  derivative_latex: string
  integral: string
  integral_latex: string
  integral_symbolic: boolean
  definite_value: number | null
  x_min: number
  x_max: number
  xs: number[]
  ys: number[] // f(x)
  dys: number[] // f'(x)
  fs: number[] // F(x) = ∫[x_min, x] f(t) dt
}

let initPromise: Promise<void> | null = null

/** Initialise the WASM module once (safe to call repeatedly). */
export function ensureEngine(): Promise<void> {
  if (!initPromise) {
    initPromise = initWasm({ module_or_path: wasmUrl }).then(() => undefined)
  }
  return initPromise
}

/** Run the full analysis pipeline (parse → diff → integrate → sample). */
export function analyze(
  input: string,
  xMin: number,
  xMax: number,
  samples = 400,
): Analysis {
  return JSON.parse(wasmProcess(input, xMin, xMax, samples)) as Analysis
}

/** Mirrors `calcsim_core::ac::AcPower` (serde JSON). */
export interface AcPowerResult {
  ok: boolean
  error?: string
  v_peak: number
  i_peak: number
  frequency: number
  phase_deg: number
  angular_freq: number
  period: number
  phase_rad: number
  rms_v: number
  rms_i: number
  avg_power: number
  apparent_power: number
  reactive_power: number
  power_factor: number
  v_latex: string
  i_latex: string
  integral_latex: string
  t0: number
  t1: number
  ts: number[]
  vs: number[]
  i_vals: number[]
  ps: number[]
}

/** Analyse a sinusoidal AC circuit (power via numerical integration). */
export function acPower(
  vPeak: number,
  iPeak: number,
  frequency: number,
  phaseDeg: number,
  samples = 600,
): AcPowerResult {
  return JSON.parse(wasmAcPower(vPeak, iPeak, frequency, phaseDeg, samples)) as AcPowerResult
}
